POST http://localhost:8080/games/6eae3c95
Content-Type: application/json

{
  "question_id": "qid_2",
  "state": "ANSWER"
}

###
GET http://localhost:8080/games/6eae3c95

###
POST http://localhost:8080/quizzes/123/start
Content-Type: application/json

{}

###
GET http://localhost:8080/quizzes/123

###

GET https://lama-api.kvarto.net/quizzes/123/start

###
POST http://lama-api.kvarto.net/quizzes/123/start
