GET http://localhost:8080/quizzes/123

###
POST http://localhost:8080/quizzes/123/start
Content-Type: application/json

{}

###
GET http://localhost:8080/games/536a3a85

###
GET http://localhost:8080/games/536a3a85/scores

###
POST http://localhost:8080/games/536a3a85
Content-Type: application/json

{
  "question_id": "qid_2",
  "state": "ANSWER"
}

###

GET https://lama-api.kvarto.net/quizzes/123

###
POST http://lama-api.kvarto.net/quizzes/123/start

