GET http://localhost:8080/quizzes/123

###
POST http://localhost:8080/quizzes/123/start
Content-Type: application/json

{}

###
GET http://localhost:8080/games/a1274d1b

###
GET http://localhost:8080/games/a1274d1b/scores

###
POST http://localhost:8080/games/a1274d1b
Content-Type: application/json

{
  "question_id": "qid_2",
  "state": "FINISH"
}

###

POST http://localhost:8080/quizzes

{
  "title": "New quizz",
  "questions": [
    {
      "id": "q1",
      "description": "Question #1",
      "answers": [
        {
          "id": "a1",
          "description": "Answer #1",
          "is_right": true
        },
        {
          "id": "a2",
          "description": "Answer #2",
          "is_right": true
        },
        {
          "id": "a3",
          "description": "Answer #3",
          "is_right": true
        },
        {
          "id": "a4",
          "description": "Answer #4",
          "is_right": true
        }
      ]
    }
  ]
}



###
GET https://lama-api.kvarto.net/quizzes/123

###
POST http://lama-api.kvarto.net/quizzes/123/start

