name: Lama CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: gradle build
        run: ./gradlew build
      - name: upload atifact
        uses: actions/upload-artifact@v2
        with:
          name: lama_jar
          path: build/libs/lama.jar
          retention-days: 5

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: lama_jar

      - name: set up gcloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Use gcloud CLI
        run: gcloud info

      - name: List artifcat files
        run: ls -la
